In [69]:
import pandas as pd

In [70]:
data = pd.read_csv("weather_classification_data.csv")
df = pd.DataFrame(data)
df

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility (km),Location,Weather Type
0,14.0,73,9.5,82.0,partly cloudy,1010.82,2,Winter,3.5,inland,Rainy
1,39.0,96,8.5,71.0,partly cloudy,1011.43,7,Spring,10.0,inland,Cloudy
2,30.0,64,7.0,16.0,clear,1018.72,5,Spring,5.5,mountain,Sunny
3,38.0,83,1.5,82.0,clear,1026.25,7,Spring,1.0,coastal,Sunny
4,27.0,74,17.0,66.0,overcast,990.67,1,Winter,2.5,mountain,Rainy
...,...,...,...,...,...,...,...,...,...,...,...
13195,10.0,74,14.5,71.0,overcast,1003.15,1,Summer,1.0,mountain,Rainy
13196,-1.0,76,3.5,23.0,cloudy,1067.23,1,Winter,6.0,coastal,Snowy
13197,30.0,77,5.5,28.0,overcast,1012.69,3,Autumn,9.0,coastal,Cloudy
13198,3.0,76,10.0,94.0,overcast,984.27,0,Winter,2.0,inland,Snowy
13199,-5.0,38,0.0,92.0,overcast,1015.37,5,Autumn,10.0,mountain,Rainy

In [71]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13200 entries, 0 to 13199
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Temperature           13200 non-null  float64
 1   Humidity              13200 non-null  int64
 2   Wind Speed            13200 non-null  float64
 3   Precipitation (%)     13200 non-null  float64
 4   Cloud Cover           13200 non-null  str
 5   Atmospheric Pressure  13200 non-null  float64
 6   UV Index              13200 non-null  int64
 7   Season                13200 non-null  str
 8   Visibility (km)       13200 non-null  float64
 9   Location              13200 non-null  str
 10  Weather Type          13200 non-null  str
dtypes: float64(5), int64(2), str(4)
memory usage: 1.1 MB

In [72]:
df.isna().sum()

Temperature             0
Humidity                0
Wind Speed              0
Precipitation (%)       0
Cloud Cover             0
Atmospheric Pressure    0
UV Index                0
Season                  0
Visibility (km)         0
Location                0
Weather Type            0
dtype: int64

In [73]:
X = df.drop("Weather Type",axis = 1)
y = df["Weather Type"]
X,y

(       Temperature  Humidity  Wind Speed  Precipitation (%)    Cloud Cover  \
 0             14.0        73         9.5               82.0  partly cloudy
 1             39.0        96         8.5               71.0  partly cloudy
 2             30.0        64         7.0               16.0          clear
 3             38.0        83         1.5               82.0          clear
 4             27.0        74        17.0               66.0       overcast
 ...            ...       ...         ...                ...            ...
 13195         10.0        74        14.5               71.0       overcast
 13196         -1.0        76         3.5               23.0         cloudy
 13197         30.0        77         5.5               28.0       overcast
 13198          3.0        76        10.0               94.0       overcast
 13199         -5.0        38         0.0               92.0       overcast

        Atmospheric Pressure  UV Index  Season  Visibility (km)  Location
 0                   1010.82         2  Winter              3.5    inland
 1                   1011.43         7  Spring             10.0    inland
 2                   1018.72         5  Spring              5.5  mountain
 3                   1026.25         7  Spring              1.0   coastal
 4                    990.67         1  Winter              2.5  mountain
 ...                     ...       ...     ...              ...       ...
 13195               1003.15         1  Summer              1.0  mountain
 13196               1067.23         1  Winter              6.0   coastal
 13197               1012.69         3  Autumn              9.0   coastal
 13198                984.27         0  Winter              2.0    inland
 13199               1015.37         5  Autumn             10.0  mountain

 [13200 rows x 10 columns],
 0         Rainy
 1        Cloudy
 2         Sunny
 3         Sunny
 4         Rainy
           ...
 13195     Rainy
 13196     Snowy
 13197    Cloudy
 13198     Snowy
 13199     Rainy
 Name: Weather Type, Length: 13200, dtype: str)

In [74]:
X = pd.get_dummies(X)
X

,Temperature,Humidity,Wind Speed,Precipitation (%),Atmospheric Pressure,UV Index,Visibility (km),Cloud Cover_clear,Cloud Cover_cloudy,Cloud Cover_overcast,Cloud Cover_partly cloudy,Season_Autumn,Season_Spring,Season_Summer,Season_Winter,Location_coastal,Location_inland,Location_mountain
0,14.0,73,9.5,82.0,1010.82,2,3.5,False,False,False,True,False,False,False,True,False,True,False
1,39.0,96,8.5,71.0,1011.43,7,10.0,False,False,False,True,False,True,False,False,False,True,False
2,30.0,64,7.0,16.0,1018.72,5,5.5,True,False,False,False,False,True,False,False,False,False,True
3,38.0,83,1.5,82.0,1026.25,7,1.0,True,False,False,False,False,True,False,False,True,False,False
4,27.0,74,17.0,66.0,990.67,1,2.5,False,False,True,False,False,False,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13195,10.0,74,14.5,71.0,1003.15,1,1.0,False,False,True,False,False,False,True,False,False,False,True
13196,-1.0,76,3.5,23.0,1067.23,1,6.0,False,True,False,False,False,False,False,True,True,False,False
13197,30.0,77,5.5,28.0,1012.69,3,9.0,False,False,True,False,True,False,False,False,True,False,False
13198,3.0,76,10.0,94.0,984.27,0,2.0,False,False,True,False,False,False,False,True,False,True,False
13199,-5.0,38,0.0,92.0,1015.37,5,10.0,False,False,True,False,True,False,False,False,False,False,True

In [75]:
# Encoding the target column using label encoding
# =================================================

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

print(le.classes_)

['Cloudy' 'Rainy' 'Snowy' 'Sunny']

In [76]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3,random_state = 42)

In [77]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit_transform(X_train)
scaler.transform(X_test)

array([[ 0.20716367, -1.51752888, -0.76847391, ..., -0.61838964,
         1.32349457, -0.74992954],
       [ 2.4564406 ,  1.26201733,  0.68198037, ..., -0.61838964,
         1.32349457, -0.74992954],
       [ 1.18761772, -0.87227708, -1.13108748, ..., -0.61838964,
        -0.75557545,  1.3334586 ],
       ...,
       [-0.94631168, -0.17739053,  1.40720751, ..., -0.61838964,
        -0.75557545,  1.3334586 ],
       [ 0.72622758, -1.31898986, -0.84099662, ...,  1.61710342,
        -0.75557545, -0.74992954],
       [ 0.20716367, -2.26205018, -0.98604205, ...,  1.61710342,
        -0.75557545, -0.74992954]], shape=(3960, 18))

In [78]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
y_pred

array([3, 3, 0, ..., 2, 0, 0], shape=(3960,))

In [80]:
le.inverse_transform(y_pred)

array(['Sunny', 'Sunny', 'Cloudy', ..., 'Snowy', 'Cloudy', 'Cloudy'],
      shape=(3960,), dtype=object)

In [ ]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_test,y_pred))

# number of correct predictions / total number of elements in y_test
# return the accuracy score

0.7906565656565656