In [1]:
import pandas as pd

In [3]:
data = pd.read_csv("Lifestyle_and_Health_Risk_Prediction_Synthetic_Dataset (1).csv")
df = pd.DataFrame(data)
df

,age,weight,height,exercise,sleep,sugar_intake,smoking,alcohol,married,profession,bmi,health_risk
0,56,67,195,low,6.1,medium,yes,yes,yes,office_worker,17.6,high
1,69,76,170,high,6.9,high,no,no,no,teacher,26.3,high
2,46,106,153,high,6.6,low,yes,no,no,artist,45.3,high
3,32,54,186,medium,8.5,medium,no,no,no,artist,15.6,low
4,60,98,195,high,8.0,low,no,no,yes,teacher,25.8,high
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,42,75,187,medium,7.2,low,no,no,yes,driver,21.4,low
4996,39,86,183,low,7.4,low,no,no,yes,engineer,25.7,high
4997,48,56,194,none,7.2,high,yes,yes,yes,engineer,14.9,high
4998,34,109,148,medium,9.9,medium,no,no,yes,doctor,49.8,low
4999,72,47,149,high,6.3,medium,no,no,yes,driver,21.2,low

In [15]:
# columns,shape,describe,info
df.columns,df.shape,df.describe(),df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   age           5000 non-null   int64
 1   weight        5000 non-null   int64
 2   height        5000 non-null   int64
 3   exercise      5000 non-null   str
 4   sleep         5000 non-null   float64
 5   sugar_intake  5000 non-null   str
 6   smoking       5000 non-null   str
 7   alcohol       5000 non-null   str
 8   married       5000 non-null   str
 9   profession    5000 non-null   str
 10  bmi           5000 non-null   float64
 11  health_risk   5000 non-null   str
dtypes: float64(2), int64(3), str(7)
memory usage: 468.9 KB

(Index(['age', 'weight', 'height', 'exercise', 'sleep', 'sugar_intake',
        'smoking', 'alcohol', 'married', 'profession', 'bmi', 'health_risk'],
       dtype='str'),
 (5000, 12),
                age       weight       height        sleep         bmi
 count  5000.000000  5000.000000  5000.000000  5000.000000  5000.00000
 mean     48.805600    77.359200   171.933200     6.997060    26.84388
 std      17.906991    18.714567    15.822225     1.432849     8.25249
 min      18.000000    45.000000   145.000000     3.000000    11.40000
 25%      34.000000    61.000000   158.000000     6.000000    20.30000
 50%      49.000000    77.000000   171.500000     7.000000    26.00000
 75%      64.000000    94.000000   186.000000     8.000000    32.40000
 max      79.000000   109.000000   199.000000    10.000000    51.40000,
 None)

In [ ]:
# missing values
df.isna().sum()
# fillna() used to fill the missing values
# df["age"].fillna(df["age"].mean())
# df["age"].fillna(df["age"].median())
# df["exersice"].fillna(df["exercise"].mode())
# to fill missing values with the mode(the most frequent value)

age             0
weight          0
height          0
exercise        0
sleep           0
sugar_intake    0
smoking         0
alcohol         0
married         0
profession      0
bmi             0
health_risk     0
dtype: int64

In [19]:
# split the target and features
X = df.drop("health_risk",axis = 1)
y = df["health_risk"]
X,y
X.dtypes

age               int64
weight            int64
height            int64
exercise            str
sleep           float64
sugar_intake        str
smoking             str
alcohol             str
married             str
profession          str
bmi             float64
dtype: object

In [20]:
# Encodind >>> converting the string values in X into numerical values
# the column proffession has multiple values we are choosing one hot encoding

X = pd.get_dummies(X)
X

,age,weight,height,sleep,bmi,exercise_high,exercise_low,exercise_medium,exercise_none,sugar_intake_high,...,married_no,married_yes,profession_artist,profession_doctor,profession_driver,profession_engineer,profession_farmer,profession_office_worker,profession_student,profession_teacher
0,56,67,195,6.1,17.6,False,True,False,False,False,...,False,True,False,False,False,False,False,True,False,False
1,69,76,170,6.9,26.3,True,False,False,False,True,...,True,False,False,False,False,False,False,False,False,True
2,46,106,153,6.6,45.3,True,False,False,False,False,...,True,False,True,False,False,False,False,False,False,False
3,32,54,186,8.5,15.6,False,False,True,False,False,...,True,False,True,False,False,False,False,False,False,False
4,60,98,195,8.0,25.8,True,False,False,False,False,...,False,True,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,42,75,187,7.2,21.4,False,False,True,False,False,...,False,True,False,False,True,False,False,False,False,False
4996,39,86,183,7.4,25.7,False,True,False,False,False,...,False,True,False,False,False,True,False,False,False,False
4997,48,56,194,7.2,14.9,False,False,False,True,True,...,False,True,False,False,False,True,False,False,False,False
4998,34,109,148,9.9,49.8,False,False,True,False,False,...,False,True,False,True,False,False,False,False,False,False
4999,72,47,149,6.3,21.2,True,False,False,False,False,...,False,True,False,False,True,False,False,False,False,False

In [21]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3,random_state = 42)

In [ ]:
# age = 25 - 75
# weight =40 -130
# height = 130 - 197

# scaling
# ====================
# Feature scaling in machine learning is the process of changing numerical columns 
# to use the same value range

In [22]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train) # mean + std deviation
scaler.transform(X_train)
# scaler.fit_transform(X_train)

scaler.transform(X_test)
#if we allow to fit the X-test it may occur the data leakage
#  
# fit(): learns and stores stats like mean and standerd deviation fro your dataset,
# but does not change the data
# transform(): uses the pre-calculated stats to scale or change the data

array([[-1.65787335,  0.9065587 ,  0.55608827, ..., -0.35463208,
         2.65791575, -0.37672929],
       [-0.20837704,  0.47493749, -0.70705152, ..., -0.35463208,
        -0.37623465, -0.37672929],
       [-0.98887505,  1.33817991, -0.39126657, ..., -0.35463208,
        -0.37623465, -0.37672929],
       ...,
       [-1.37912406, -0.92783146, -1.59124936, ...,  2.81982387,
        -0.37623465, -0.37672929],
       [ 1.51986855, -0.33435229,  0.87187321, ..., -0.35463208,
        -0.37623465, -0.37672929],
       [ 0.68362069,  0.25912688, -1.21230743, ..., -0.35463208,
        -0.37623465, -0.37672929]], shape=(1500, 26))

In [24]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors = 5)
model.fit(X_train,y_train)

KNeighborsClassifier()

In [25]:
y_pred = model.predict(X_test)
y_pred

array(['low', 'high', 'high', ..., 'high', 'high', 'high'],
      shape=(1500,), dtype=object)

In [26]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_test,y_pred))

0.7993333333333333