In [16]:
import pandas as pd

In [17]:
data = pd.read_csv("diabetes_risk_prediction_dataset.csv")
data = data.drop(["Patient_ID","Age","Gender","Country","Height_cm","Weight_kg","Work_Type","Residence_Type","AI_Health_Recommendation","Doctor_Consultation_Needed"],axis = 1)
df = pd.DataFrame(data)
df

,BMI,Waist_Circumference_cm,Blood_Glucose,HbA1c,Fasting_Blood_Sugar,Insulin_Level,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Total_Cholesterol,HDL,...,Alcohol_Consumption,Family_History_Diabetes,Hypertension,Heart_Disease,Fatty_Liver,PCOS,Medication_Adherence,Daily_Water_Intake_L,Diabetes_Risk_Score,Diabetes_Risk
0,19.8,71.2,88.4,10.4,149.5,27.4,94,61,138.7,40.1,...,Never,Yes,No,Yes,Yes,No,Good,4.4,60,Moderate
1,45.9,121.8,247.3,11.3,199.3,18.3,148,100,286.8,35.6,...,Frequently,Yes,No,Yes,Yes,Yes,Average,2.1,99,High
2,37.9,131.8,141.9,6.3,219.6,23.9,101,108,129.4,32.1,...,Frequently,Yes,No,No,Yes,No,Average,2.8,80,High
3,26.3,99.1,90.1,7.4,217.7,36.7,120,63,168.2,61.9,...,Occasionally,Yes,Yes,No,No,No,Average,1.5,82,High
4,41.4,77.1,93.8,12.0,153.5,22.3,190,90,281.5,37.4,...,Occasionally,No,Yes,Yes,Yes,Yes,Poor,1.6,93,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,45.3,75.9,248.8,9.9,191.5,15.4,97,94,193.1,64.7,...,Occasionally,Yes,No,No,No,Yes,Average,3.5,86,High
49996,19.8,114.5,198.4,6.3,110.0,13.3,121,120,127.2,86.1,...,Occasionally,No,No,Yes,Yes,No,Average,3.4,49,Moderate
49997,17.4,96.1,118.8,NaN,208.4,30.5,176,119,137.6,54.7,...,Frequently,Yes,Yes,No,Yes,Yes,Poor,2.6,100,High
49998,26.2,131.4,139.5,9.2,84.7,14.8,141,82,306.8,72.2,...,Never,No,No,No,Yes,Yes,Good,2.7,52,Moderate
49999,40.5,66.1,123.5,6.8,195.3,31.7,166,107,316.0,47.5,...,Frequently,No,Yes,No,Yes,Yes,Good,3.9,91,High

In [18]:
df.columns

Index(['BMI', 'Waist_Circumference_cm', 'Blood_Glucose', 'HbA1c',
       'Fasting_Blood_Sugar', 'Insulin_Level', 'Blood_Pressure_Systolic',
       'Blood_Pressure_Diastolic', 'Total_Cholesterol', 'HDL', 'LDL',
       'Triglycerides', 'Heart_Rate', 'Physical_Activity_Level',
       'Exercise_Hours_Per_Week', 'Daily_Walking_Minutes', 'Diet_Quality',
       'Sugar_Intake_Level', 'Sleep_Hours', 'Stress_Level', 'Smoking_Status',
       'Alcohol_Consumption', 'Family_History_Diabetes', 'Hypertension',
       'Heart_Disease', 'Fatty_Liver', 'PCOS', 'Medication_Adherence',
       'Daily_Water_Intake_L', 'Diabetes_Risk_Score', 'Diabetes_Risk'],
      dtype='str')

In [19]:
df.shape

(50000, 31)

In [20]:
df.describe()

,BMI,Waist_Circumference_cm,Blood_Glucose,HbA1c,Fasting_Blood_Sugar,Insulin_Level,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Total_Cholesterol,HDL,LDL,Triglycerides,Heart_Rate,Exercise_Hours_Per_Week,Daily_Walking_Minutes,Sleep_Hours,Daily_Water_Intake_L,Diabetes_Risk_Score
count,50000.000000,50000.000000,49041.000000,48026.000000,50000.000000,50000.000000,50000.000000,50000.000000,49000.000000,49000.000000,49000.000000,49000.000000,50000.000000,48008.000000,48036.000000,47983.000000,50000.000000,50000.000000
mean,30.924056,99.960790,159.905245,8.488061,142.607294,23.476724,140.171120,90.039000,220.168635,57.371731,135.014524,229.543259,85.124260,5.017460,89.933442,6.500917,2.998842,74.043920
std,10.290091,23.086579,52.040575,2.313758,44.681799,12.403841,29.168623,17.575503,57.793626,18.720696,49.135613,98.234911,20.390334,2.875922,52.034642,2.027793,1.152273,15.598327
min,11.900000,60.000000,70.000000,4.500000,65.000000,2.000000,90.000000,60.000000,120.000000,25.000000,50.000000,60.000000,50.000000,0.000000,0.000000,3.000000,1.000000,13.000000
25%,22.700000,80.000000,114.700000,6.500000,103.900000,12.800000,115.000000,75.000000,169.800000,41.300000,92.500000,144.700000,68.000000,2.500000,44.900000,4.700000,2.000000,64.000000
50%,30.000000,99.800000,159.900000,8.500000,142.600000,23.400000,140.000000,90.000000,220.400000,57.300000,135.100000,229.500000,85.000000,5.000000,89.800000,6.500000,3.000000,75.000000
75%,37.800000,119.900000,205.100000,10.500000,181.500000,34.300000,165.000000,105.000000,270.500000,73.600000,177.700000,314.600000,103.000000,7.500000,135.200000,8.300000,4.000000,86.000000
max,61.700000,140.000000,250.000000,12.500000,220.000000,45.000000,190.000000,120.000000,320.000000,90.000000,220.000000,400.000000,120.000000,10.000000,180.000000,10.000000,5.000000,100.000000

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 31 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   BMI                       50000 non-null  float64
 1   Waist_Circumference_cm    50000 non-null  float64
 2   Blood_Glucose             49041 non-null  float64
 3   HbA1c                     48026 non-null  float64
 4   Fasting_Blood_Sugar       50000 non-null  float64
 5   Insulin_Level             50000 non-null  float64
 6   Blood_Pressure_Systolic   50000 non-null  int64
 7   Blood_Pressure_Diastolic  50000 non-null  int64
 8   Total_Cholesterol         49000 non-null  float64
 9   HDL                       49000 non-null  float64
 10  LDL                       49000 non-null  float64
 11  Triglycerides             49000 non-null  float64
 12  Heart_Rate                50000 non-null  int64
 13  Physical_Activity_Level   49500 non-null  str
 14  Exercise_Hours_Per_Week   48008 non-null  float64
 15  Daily_Walking_Minutes     48036 non-null  float64
 16  Diet_Quality              50000 non-null  str
 17  Sugar_Intake_Level        50000 non-null  str
 18  Sleep_Hours               47983 non-null  float64
 19  Stress_Level              50000 non-null  str
 20  Smoking_Status            50000 non-null  str
 21  Alcohol_Consumption       50000 non-null  str
 22  Family_History_Diabetes   50000 non-null  str
 23  Hypertension              50000 non-null  str
 24  Heart_Disease             50000 non-null  str
 25  Fatty_Liver               50000 non-null  str
 26  PCOS                      50000 non-null  str
 27  Medication_Adherence      49000 non-null  str
 28  Daily_Water_Intake_L      50000 non-null  float64
 29  Diabetes_Risk_Score       50000 non-null  int64
 30  Diabetes_Risk             50000 non-null  str
dtypes: float64(14), int64(4), str(13)
memory usage: 11.8 MB

In [22]:
df.isna().sum()

BMI                            0
Waist_Circumference_cm         0
Blood_Glucose                959
HbA1c                       1974
Fasting_Blood_Sugar            0
Insulin_Level                  0
Blood_Pressure_Systolic        0
Blood_Pressure_Diastolic       0
Total_Cholesterol           1000
HDL                         1000
LDL                         1000
Triglycerides               1000
Heart_Rate                     0
Physical_Activity_Level      500
Exercise_Hours_Per_Week     1992
Daily_Walking_Minutes       1964
Diet_Quality                   0
Sugar_Intake_Level             0
Sleep_Hours                 2017
Stress_Level                   0
Smoking_Status                 0
Alcohol_Consumption            0
Family_History_Diabetes        0
Hypertension                   0
Heart_Disease                  0
Fatty_Liver                    0
PCOS                           0
Medication_Adherence        1000
Daily_Water_Intake_L           0
Diabetes_Risk_Score            0
Diabetes_Risk                  0
dtype: int64

In [29]:
df = df.fillna({
    "Blood_Glucose": df["Blood_Glucose"].mean(),
    "HbA1c": df["HbA1c"].mean(),
    "Total_Cholesterol": df["Total_Cholesterol"].mean(),
    "HDL": df["HDL"].mean(),
    "LDL": df["LDL"].mean(),
    "Triglycerides": df["Triglycerides"].mean(),
    "Physical_Activity_Level": df["Physical_Activity_Level"].max(),
    "Exercise_Hours_Per_Week": df["Exercise_Hours_Per_Week"].mean(),
    "Daily_Walking_Minutes": df["Daily_Walking_Minutes"].mean(),
    "Sleep_Hours": df["Sleep_Hours"].mean(),
    "Medication_Adherence": df["Medication_Adherence"].max()
})

In [30]:
df.isna().sum()

BMI                         0
Waist_Circumference_cm      0
Blood_Glucose               0
HbA1c                       0
Fasting_Blood_Sugar         0
Insulin_Level               0
Blood_Pressure_Systolic     0
Blood_Pressure_Diastolic    0
Total_Cholesterol           0
HDL                         0
LDL                         0
Triglycerides               0
Heart_Rate                  0
Physical_Activity_Level     0
Exercise_Hours_Per_Week     0
Daily_Walking_Minutes       0
Diet_Quality                0
Sugar_Intake_Level          0
Sleep_Hours                 0
Stress_Level                0
Smoking_Status              0
Alcohol_Consumption         0
Family_History_Diabetes     0
Hypertension                0
Heart_Disease               0
Fatty_Liver                 0
PCOS                        0
Medication_Adherence        0
Daily_Water_Intake_L        0
Diabetes_Risk_Score         0
Diabetes_Risk               0
dtype: int64

In [31]:
X = df.drop("Diabetes_Risk",axis = 1)
y = df["Diabetes_Risk"]
X,y

(        BMI  Waist_Circumference_cm  Blood_Glucose      HbA1c  \
 0      19.8                    71.2           88.4  10.400000
 1      45.9                   121.8          247.3  11.300000
 2      37.9                   131.8          141.9   6.300000
 3      26.3                    99.1           90.1   7.400000
 4      41.4                    77.1           93.8  12.000000
 ...     ...                     ...            ...        ...
 49995  45.3                    75.9          248.8   9.900000
 49996  19.8                   114.5          198.4   6.300000
 49997  17.4                    96.1          118.8   8.488061
 49998  26.2                   131.4          139.5   9.200000
 49999  40.5                    66.1          123.5   6.800000

        Fasting_Blood_Sugar  Insulin_Level  Blood_Pressure_Systolic  \
 0                    149.5           27.4                       94
 1                    199.3           18.3                      148
 2                    219.6           23.9                      101
 3                    217.7           36.7                      120
 4                    153.5           22.3                      190
 ...                    ...            ...                      ...
 49995                191.5           15.4                       97
 49996                110.0           13.3                      121
 49997                208.4           30.5                      176
 49998                 84.7           14.8                      141
 49999                195.3           31.7                      166

        Blood_Pressure_Diastolic  Total_Cholesterol   HDL  ...  Smoking_Status  \
 0                            61              138.7  40.1  ...          Former
 1                           100              286.8  35.6  ...         Current
 2                           108              129.4  32.1  ...           Never
 3                            63              168.2  61.9  ...         Current
 4                            90              281.5  37.4  ...           Never
 ...                         ...                ...   ...  ...             ...
 49995                        94              193.1  64.7  ...          Former
 49996                       120              127.2  86.1  ...         Current
 49997                       119              137.6  54.7  ...           Never
 49998                        82              306.8  72.2  ...           Never
 49999                       107              316.0  47.5  ...          Former

        Alcohol_Consumption  Family_History_Diabetes Hypertension  \
 0                    Never                      Yes           No
 1               Frequently                      Yes           No
 2               Frequently                      Yes           No
 3             Occasionally                      Yes          Yes
 4             Occasionally                       No          Yes
 ...                    ...                      ...          ...
 49995         Occasionally                      Yes           No
 49996         Occasionally                       No           No
 49997           Frequently                      Yes          Yes
 49998                Never                       No           No
 49999           Frequently                       No          Yes

        Heart_Disease  Fatty_Liver PCOS Medication_Adherence  \
 0                Yes          Yes   No                 Good
 1                Yes          Yes  Yes              Average
 2                 No          Yes   No              Average
 3                 No           No   No              Average
 4                Yes          Yes  Yes                 Poor
 ...              ...          ...  ...                  ...
 49995             No           No  Yes              Average
 49996            Yes          Yes   No              Average
 49997             No          Yes  Yes                 Poor
 49998             No          Yes  Yes                 Good
 49999             No          Yes  Yes                 Good

        Daily_Water_Intake_L Diabetes_Risk_Score
 0                       4.4                  60
 1                       2.1                  99
 2                       2.8                  80
 3                       1.5                  82
 4                       1.6                  93
 ...                     ...                 ...
 49995                   3.5                  86
 49996                   3.4                  49
 49997                   2.6                 100
 49998                   2.7                  52
 49999                   3.9                  91

 [50000 rows x 30 columns],
 0        Moderate
 1            High
 2            High
 3            High
 4            High
            ...
 49995        High
 49996    Moderate
 49997        High
 49998    Moderate
 49999        High
 Name: Diabetes_Risk, Length: 50000, dtype: str)

In [32]:
X = pd.get_dummies(X)
X.head()

,BMI,Waist_Circumference_cm,Blood_Glucose,HbA1c,Fasting_Blood_Sugar,Insulin_Level,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Total_Cholesterol,HDL,...,Hypertension_Yes,Heart_Disease_No,Heart_Disease_Yes,Fatty_Liver_No,Fatty_Liver_Yes,PCOS_No,PCOS_Yes,Medication_Adherence_Average,Medication_Adherence_Good,Medication_Adherence_Poor
0,19.8,71.2,88.4,10.4,149.5,27.4,94,61,138.7,40.1,...,False,False,True,False,True,True,False,False,True,False
1,45.9,121.8,247.3,11.3,199.3,18.3,148,100,286.8,35.6,...,False,False,True,False,True,False,True,True,False,False
2,37.9,131.8,141.9,6.3,219.6,23.9,101,108,129.4,32.1,...,False,True,False,False,True,True,False,True,False,False
3,26.3,99.1,90.1,7.4,217.7,36.7,120,63,168.2,61.9,...,True,True,False,True,False,True,False,True,False,False
4,41.4,77.1,93.8,12.0,153.5,22.3,190,90,281.5,37.4,...,True,False,True,False,True,False,True,False,False,True

In [33]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3,random_state = 42)

In [34]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train,X_test

(array([[ 1.16407445,  0.68847306,  0.05147632, ...,  1.43182015,
         -0.69768744, -0.72534021],
        [-0.72594148, -0.46960426,  0.06308608, ..., -0.69841174,
         -0.69768744,  1.37866339],
        [ 0.8425769 , -0.63442425,  0.41718381, ..., -0.69841174,
         -0.69768744,  1.37866339],
        ...,
        [-1.18383194, -1.14189633, -0.21361324, ..., -0.69841174,
          1.43330658, -0.72534021],
        [ 0.77438045,  0.47160465,  1.46399734, ...,  1.43182015,
         -0.69768744, -0.72534021],
        [-0.02449227,  0.3414836 ,  1.01895647, ..., -0.69841174,
          1.43330658, -0.72534021]], shape=(35000, 49)),
 array([[ 0.61850284, -1.58430789, -0.8250607 , ...,  1.43182015,
         -0.69768744, -0.72534021],
        [ 1.44660261,  0.18967572, -0.21361324, ..., -0.69841174,
          1.43330658, -0.72534021],
        [ 1.67067666, -0.65611109,  0.76934659, ...,  1.43182015,
         -0.69768744, -0.72534021],
        ...,
        [-0.17062752,  1.09618567,  0.35526508, ..., -0.69841174,
          1.43330658, -0.72534021],
        [-0.35573217,  0.36317044, -0.57932074, ...,  1.43182015,
         -0.69768744, -0.72534021],
        [-0.56032153, -0.93804002, -1.02436161, ...,  1.43182015,
         -0.69768744, -0.72534021]], shape=(15000, 49)))

In [36]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
y_pred

array(['High', 'High', 'High', ..., 'Moderate', 'High', 'High'],
      shape=(15000,), dtype=object)

In [37]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_test,y_pred))

0.824