In [1]:
import pandas as pd

In [ ]:
data_1 = pd.read_csv("custom_windows (1).csv")
df_1 = pd.DataFrame(data_1)

data_2 = pd.read_csv("order_windows (1).csv")
df_2 = pd.DataFrame(data_2)

   id      name  age   location  salary
0   1      Ross   32  Ahmedabad    2000
1   2    Rachel   25      Delhi    1500
2   3  Chandler   23       Kota    2000
3   4    Monika   25     Mumbai    6500
4   5      Mike   27     Bhopal    8500
5   6    Phoebe   22         MP    4500
6   7      Joey   24     Indore   10000

In [21]:
result = pd.merge(df_1,df_2,on = "id",how = "inner")
# result = pd.merge(df_1,df_2,on = "id",how = "left")
# result = pd.merge(df_1,df_2,on = "id",how = "right")
# result = pd.merge(df_1,df_2,on = "id",how = "outer")
result.sort_values("amount",ascending = False)

# return the result with salary in ascending order
result.sort_values("salary")

   id      name  age location  salary  oid               dat  amount
0   2    Rachel   25    Delhi    1500  101  20-11-2016 00:00    1560
1   3  Chandler   23     Kota    2000  102  08-10-2016 00:00    3000
2   3  Chandler   23     Kota    2000  100  08-10-2016 00:00    1500
3   4    Monika   25   Mumbai    6500  103  20-05-2015 00:00    2060

In [34]:
result.loc[result["salary"] > 2000]
pd.merge(df_1,df_2,on = "id",how = "inner")["salary"] > 2000

0    False
1    False
2    False
3     True
Name: salary, dtype: bool