In [59]:
import pandas as pd

In [60]:
data = pd.read_csv("customer5_windows.csv")
df = pd.DataFrame(data)
df

,id,fname,lname,age,prof,loc,salary
0,4000001,Kristina,Chung,55,Pilot,india,45000
1,4000002,Paige,Chen,74,Teacher,uk,45987
2,4000003,Sherri,Melton,34,Firefighter,us,78956
3,4000004,Gretchen,Hill,66,Computer hardware engineer,china,98570
4,4000005,Karen,Puckett,74,Lawyer,africa,45680
...,...,...,...,...,...,...,...
68,4000069,Melanie,Hewitt,47,Real estate agent,us,456987
69,4000070,Marianne,Branch,53,Judge,us,258974
70,4000071,Natalie,Walton,24,Recreation and fitness worker,us,7896254
71,4000072,Caroline,O'Brien,44,Computer support specialist,us,478921
72,4000073,Arlene,Case,62,Musician,us,159879

In [101]:
df.iloc[0:10]
df.iloc[-10:,:]
df.sample(10)
df.shape
df.columns
df.dtypes
df.info()
df.describe()
df["prof"].unique()
df["loc"].unique()

df[["fname","lname","salary"]]
df[df["salary"] > 100000]
df[df["age"] > 50]
df[df["prof"] == "Pilot"]
df[df["loc"] == "india"]
df.loc[(df["salary"] >= 50000) & (df["salary"] <= 100000)]
df.loc[(df["age"] < 30) & (df["salary"] > 50000)]
df.loc[(df["loc"] == "india") | (df["loc"] == "uk")]
df.loc[(df["prof"].str.contains("Computer")) & (df["salary"] >  50000)]
df.loc[df["prof"] != "Pilot"]

df.iloc[:10,:5]
df.iloc[20:31]
df.iloc[:,[1,4,6]]
df.loc[df["salary"] > 100000,["fname","lname","salary"]]
df.loc[(df["loc"] == "india") & (df["age"] > 40)]
df.loc[df["salary"] < 30000,"salary"] += 5000
df.loc[(df["prof"] == "Pilot") & (df["loc"] == "india"),"loc"] = "India"

df.sort_values("salary")
df.sort_values("salary",ascending = False).head(10)
df.sort_values(["loc","salary"],ascending = [True,False])
df["salary"].mean()
df["salary"].max()
df["salary"].min()
df["age"].mean()
df["loc"].value_counts()

df.groupby("prof")["salary"].mean()
df.groupby("loc")["salary"].max()
df.groupby("prof")["salary"].min()
df.groupby("prof").size()
df.groupby("loc")["salary"].mean().sort_values(ascending = False)
df.groupby("prof")[["salary","age"]].agg("mean")

<class 'pandas.DataFrame'>
RangeIndex: 73 entries, 0 to 72
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      73 non-null     int64
 1   fname   73 non-null     str
 2   lname   73 non-null     str
 3   age     73 non-null     int64
 4   prof    73 non-null     str
 5   loc     73 non-null     str
 6   salary  73 non-null     int64
dtypes: int64(3), str(4)
memory usage: 4.1 KB

                                       salary        age
prof
Accountant                       9.500000e+04  64.000000
Actor                            6.500000e+05  37.000000
Agricultural and food scientist  2.675000e+05  50.500000
Artist                           2.644780e+06  41.500000
Athlete                          7.194810e+05  66.000000
Carpenter                        1.629297e+05  48.666667
Childcare worker                 4.703970e+05  43.600000
Civil engineer                   2.283333e+05  60.666667
Computer hardware engineer       7.428500e+04  65.500000
Computer software engineer       8.500000e+04  47.000000
Computer support specialist      7.579737e+05  57.000000
Dancer                           5.000000e+04  28.000000
Doctor                           1.646712e+05  55.750000
Economist                        5.450000e+05  32.666667
Engineering technician           5.351833e+04  53.666667
Environmental scientist          5.878900e+04  39.000000
Financial analyst                3.000000e+04  63.000000
Firefighter                      6.447800e+04  53.500000
Human resources assistant        4.500000e+04  50.000000
Judge                            2.589740e+05  53.000000
Lawyer                           1.968933e+05  53.000000
Musician                         8.417580e+04  52.400000
Pharmacist                       3.600000e+04  52.000000
Photographer                     8.000000e+04  53.000000
Physicist                        3.000000e+04  44.000000
Pilot                            2.070000e+05  49.000000
Police officer                   5.260250e+04  42.500000
Real estate agent                2.889957e+05  41.333333
Recreation and fitness worker    7.896254e+06  24.000000
Reporter                         5.750000e+04  23.000000
Secretary                        5.225000e+06  36.000000
Social worker                    2.250000e+06  53.000000
Teacher                          2.279935e+05  50.500000
Therapist                        8.500000e+04  47.000000
Veterinarian                     5.000000e+05  42.000000
Writer                           2.483333e+05  46.000000